/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.solo_alysson;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alysson Cordeiro
 */
public class NewJFrame extends javax.swing.JFrame {

    private BancoSolo bancoSolo = new BancoSolo();
    private Solo solo = new Solo();

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        txtHal = new javax.swing.JLabel();
        cxFosforo = new javax.swing.JTextField();
        cxSolo = new javax.swing.JTextField();
        cxEnxofre = new javax.swing.JTextField();
        cxMagnesio = new javax.swing.JTextField();
        cxAluminio = new javax.swing.JTextField();
        cxPotassio = new javax.swing.JTextField();
        cxHal = new javax.swing.JTextField();
        cxCalcio = new javax.swing.JTextField();
        cadSolo = new javax.swing.JButton();
        txtSolo = new javax.swing.JLabel();
        txtFosforo = new javax.swing.JLabel();
        txtPotassio = new javax.swing.JLabel();
        txtCalcio = new javax.swing.JLabel();
        txtMagnesio = new javax.swing.JLabel();
        txtEnxofre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDados = new javax.swing.JTable();
        txtAluminio = new javax.swing.JLabel();
        txtCadSolo = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        txtProdCod = new javax.swing.JLabel();
        cxProd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Solo");

        txtHal.setText("H + AL:");

        cxFosforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxFosforoActionPerformed(evt);
            }
        });

        cxSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxSoloActionPerformed(evt);
            }
        });

        cxEnxofre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxEnxofreActionPerformed(evt);
            }
        });

        cxMagnesio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMagnesioActionPerformed(evt);
            }
        });

        cxAluminio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAluminioActionPerformed(evt);
            }
        });

        cxPotassio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPotassioActionPerformed(evt);
            }
        });

        cxHal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxHalActionPerformed(evt);
            }
        });

        cxCalcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCalcioActionPerformed(evt);
            }
        });

        cadSolo.setText("Cadastrar");
        cadSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadSoloActionPerformed(evt);
            }
        });

        txtSolo.setText("Tipo de Solo:");

        txtFosforo.setText("Fósforo:");

        txtPotassio.setText("Potássio:");

        txtCalcio.setText("Cálcio:");

        txtMagnesio.setText("Magnésio:");

        txtEnxofre.setText("Enxofre:");

        tabelaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Prod", "Fósforo", "Potássio", "Cálcio", "Magnésio", "Enxofre", "Alumínio", "H + AL"
            }
        ));
        jScrollPane1.setViewportView(tabelaDados);

        txtAluminio.setText("Alumínio:");

        txtCadSolo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtCadSolo.setText("Cadastro de Solo");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtProdCod.setText("Código Produtor:");

        cxProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(txtCadSolo)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdCod)
                            .addComponent(txtHal)
                            .addComponent(txtAluminio)
                            .addComponent(txtEnxofre)
                            .addComponent(txtMagnesio)
                            .addComponent(txtCalcio)
                            .addComponent(txtSolo)
                            .addComponent(txtFosforo)
                            .addComponent(txtPotassio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cxSolo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxFosforo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxCalcio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(cxMagnesio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(cxEnxofre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(cxPotassio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(cxAluminio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(cadSolo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(cxHal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cxProd))
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadSolo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdCod)
                    .addComponent(cxProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSolo)
                    .addComponent(cxSolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFosforo)
                    .addComponent(cxFosforo))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPotassio)
                    .addComponent(cxPotassio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalcio)
                    .addComponent(cxCalcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMagnesio)
                    .addComponent(cxMagnesio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnxofre)
                    .addComponent(cxEnxofre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAluminio)
                    .addComponent(cxAluminio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHal)
                    .addComponent(cxHal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadSolo)
                    .addComponent(btLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxFosforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxFosforoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxFosforoActionPerformed

    private void cxSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxSoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxSoloActionPerformed

    private void cxEnxofreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxEnxofreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxEnxofreActionPerformed

    private void cxMagnesioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMagnesioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxMagnesioActionPerformed

    private void cxAluminioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAluminioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAluminioActionPerformed

    private void cxPotassioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPotassioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPotassioActionPerformed

    private void cxHalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxHalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxHalActionPerformed

    private void cxCalcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCalcioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCalcioActionPerformed

    private void cadSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadSoloActionPerformed
        cadSolo();
    }//GEN-LAST:event_cadSoloActionPerformed

    public void cadSolo() { //realiza o cadastro dos dados do solo
        solo = new Solo();

        try {
            solo.setProdId(Integer.parseInt(cxProd.getText()));
            solo.setSoloId(Integer.parseInt(cxSolo.getText()));
            solo.setFosforo(Double.parseDouble(cxFosforo.getText()));
            solo.setPotassio(Double.parseDouble(cxPotassio.getText()));
            solo.setCalcio(Double.parseDouble(cxCalcio.getText()));
            solo.setMagnesio(Double.parseDouble(cxMagnesio.getText()));
            solo.setEnxofre(Double.parseDouble(cxEnxofre.getText()));
            solo.setAluminio(Double.parseDouble(cxAluminio.getText()));
            solo.setHal(Double.parseDouble(cxHal.getText()));

            if (bancoSolo.consProdCod(solo) == null) {
                bancoSolo.getBDSolo().add(solo);
                JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso!", "Cadastro OK", JOptionPane.INFORMATION_MESSAGE);
                cxProd.setText("");
                cxSolo.setText("");
                cxFosforo.setText("");
                cxPotassio.setText("");
                cxCalcio.setText("");
                cxMagnesio.setText("");
                cxEnxofre.setText("");
                cxAluminio.setText("");
                cxHal.setText("");
                cxProd.requestFocus();
                showTabSolo();
            } else {
                JOptionPane.showMessageDialog(null, "Já existe um cadastro com este código!", "ERRO Cadastro", 0);
                cxProd.setText("");
                cxProd.requestFocus();
            }

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "O Código deve ser um inteiro!", "Erro de Código", JOptionPane.ERROR_MESSAGE);

            cxProd.setText("");
            cxProd.requestFocus();
        }
    }
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        cxProd.setText("");
        cxSolo.setText("");
        cxFosforo.setText("");
        cxPotassio.setText("");
        cxCalcio.setText("");
        cxMagnesio.setText("");
        cxEnxofre.setText("");
        cxAluminio.setText("");
        cxHal.setText("");
        cxProd.requestFocus();
    }//GEN-LAST:event_btLimparActionPerformed

    private void cxProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxProdActionPerformed

    public void showTabSolo() {

        solo = new Solo();

        DefaultTableModel modTabSolo = new DefaultTableModel();

        modTabSolo = (DefaultTableModel) tabelaDados.getModel();

        modTabSolo.setRowCount(0);

        for (int posLinha = 0; posLinha < bancoSolo.getBDSolo().size(); posLinha++) {

            solo.setProdId(bancoSolo.getBDSolo().get(posLinha).getProdId());
            solo.setFosforo(bancoSolo.getBDSolo().get(posLinha).getFosforo());
            solo.setPotassio(bancoSolo.getBDSolo().get(posLinha).getPotassio());
            solo.setCalcio(bancoSolo.getBDSolo().get(posLinha).getCalcio());
            solo.setMagnesio(bancoSolo.getBDSolo().get(posLinha).getMagnesio());
            solo.setEnxofre(bancoSolo.getBDSolo().get(posLinha).getEnxofre());
            solo.setAluminio(bancoSolo.getBDSolo().get(posLinha).getAluminio());
            solo.setHal(bancoSolo.getBDSolo().get(posLinha).getHal());

            modTabSolo.insertRow(posLinha, new Object[]{solo.getProdId(),
                solo.getFosforo(), solo.getPotassio(),
                solo.getCalcio(), solo.getMagnesio(), solo.getEnxofre(),
                solo.getAluminio(), solo.getHal()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton cadSolo;
    private javax.swing.JTextField cxAluminio;
    private javax.swing.JTextField cxCalcio;
    private javax.swing.JTextField cxEnxofre;
    private javax.swing.JTextField cxFosforo;
    private javax.swing.JTextField cxHal;
    private javax.swing.JTextField cxMagnesio;
    private javax.swing.JTextField cxPotassio;
    private javax.swing.JTextField cxProd;
    private javax.swing.JTextField cxSolo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDados;
    private javax.swing.JLabel txtAluminio;
    private javax.swing.JLabel txtCadSolo;
    private javax.swing.JLabel txtCalcio;
    private javax.swing.JLabel txtEnxofre;
    private javax.swing.JLabel txtFosforo;
    private javax.swing.JLabel txtHal;
    private javax.swing.JLabel txtMagnesio;
    private javax.swing.JLabel txtPotassio;
    private javax.swing.JLabel txtProdCod;
    private javax.swing.JLabel txtSolo;
    // End of variables declaration//GEN-END:variables
}
